config/routes.rb
Rails.application.routes.draw do
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/post2.rb
class Post2 < ActiveRecord::Base
end

app/models/post3.rb
class Post3 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts=Post.all
	end

	def show
		@post=Post.find(params[:id])
	end

	def new
		@post1=Post.new
	end

	def create
		@post=Post.new(params.require(:post).permit(:title, :content))
		if @post.save
			redirect_to posts_path,:notice=>"Sucessful created!"
		else
			render"new"
		end
	end

	def edit
		@post=Post.find(params[:id])
	end

	def update
		#@post=Post.update(params.require(:post).permit(:title, :content))
		@post=Post.find(params[:id])
		if @post.update(params.require(:post).permit(:title, :content))
			redirect_to posts_path,:notice=>"Sucessful created!"
		else
			render"edit"
		end
	end

	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to posts_path,:notice=>"Sucessful created!"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1> Edit a created post</h1>
	<%=form_for @post do |f|%>
	<p>
		<%=f.label:title %><br/>
		<%=f.text_field:title %>
	</p>
	<p>
		<%=f.label:content %><br/>
		<%=f.text_field:content %>
	</p>
	<p>
		<%=f.submit"Edit a created post" %><br/>
	</p>
	<%end%>	

app/views/posts/index.html.erb
<h1> My blog</h1>
<% @posts.each do |post|%>
	<h2><%=post.title%></h2>
	<p><%=post.content%></p>
	<small><%=post.created_at%></small>
	 <p><%= link_to 'Show', post_path(post) %></p>
    <p><%= link_to 'Edit', edit_post_path(post) %></p>
    <p><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<%end%>	
<p>&nbsp;</p>
 <p><%= link_to 'New', new_post_path %></p>

app/views/posts/new.html.erb
<h1> Create a New post</h1>
	<%=form_for @post1 do |f|%>
	<p>
		<%=f.label:title %><br/>
		<%=f.text_field:title %>
	</p>
	<p>
		<%=f.label:content %><br/>
		<%=f.text_field:content %>
	</p>
	<p>
		<%=f.submit"Create a new post" %><br/>
	</p>
	<%end%>	

app/views/posts/show.html.erb
<h1> My blog1121</h1>

	<h2><%=@post.title%></h2>
	<p><%=@post.content%></p>
	<small><%=@post.created_at%></small>